### ISSUE TITLE
Data orientation of validation results

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#14]
Basic idea: return raw atomic data in an object and let the app rendering make it into something fit for human consumption. For example consider the location field:

```json
location: " with ID 'r3jx' in line 67 en jud book package from unfoldingword"
```

- Put the line number in the dedicated field for that
- Don't need "jud" since we already have bookID field
- You can add a langId and ownerId and remove both "en" and "unfoldingword"

After this, then "location" is left with only "r3jx". But for human consumption, it would be trivial to reconstruct the longer messages based on the data fields.

Here is a picture from the console log:
![image](https://user-images.githubusercontent.com/1289437/92238352-0e87d500-ee87-11ea-922b-7523ad21e726.png)

**Comment by mandolyte** [comment]
@RobH123 @PhotoNomad0 
Until this is done, I am using regex to remove surplus information from the location field.

Also, based on discussions, @RobH123 has a better idea, namely, add two fields:
- one to capture the id (`r3jx` in the above)
- one to capture the field name (in TN this would be the column header; in other resource types, not sure what it might be).

**Comment by RobH123** [comment]
I think that the essence of this is achieved now by 1/ converting notices from arrays to objects, 2/ adding extra (optional) notice fields, and 3/ removing that information from the `location` field.
