### ISSUE TITLE
Possible false notices for the tN resource for book of Acts

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#218]
- using v2.2.5
- attached results which only includes "high" priority (I think above 800?); can verify if needed.
[Validation-en_tn_45-ACT.tsv-2021-10-02T14_31_08.509Z.xlsx](https://github.com/unfoldingWord/uw-content-validation/files/7271674/Validation-en_tn_45-ACT.tsv-2021-10-02T14_31_08.509Z.xlsx)

**Comment by RobH123** [comment]
Seems that I can't duplicate these now @mandolyte.
