### ISSUE TITLE
TWL CV Results for Book of Acts

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#221]
[Validation-twl_ACT.tsv-2021-10-04T13_04_06.096Z.xlsx](https://github.com/unfoldingWord/uw-content-validation/files/7278211/Validation-twl_ACT.tsv-2021-10-04T13_04_06.096Z.xlsx)
Attached are the results of checking TWL for Acts.

This issue will document my findings.

**Comment by mandolyte** [comment]
Here is tc-create UI for the first notice on Acts 3:20:
![image](https://user-images.githubusercontent.com/1289437/135857741-45584a5d-ebcc-4b6d-85b6-07cb35d9a09c.png)

**Hypothesis**: tc-create ignores punctuation (in this a comma) and will find the original quote. But the missing comma is treated as a CV error.

**Comment by RobH123** [comment]
I think [this Zulip response](https://unfoldingword.zulipchat.com/#narrow/stream/207526-Tools--.20UR/topic/Content.20Validation.20package/near/256163350) is saying that the comma should actually be in the snippet (even if tCC gets it right without the comma).

**Comment by RobH123** [comment]
I think this can probably be closed @mandolyte ?
