### ISSUE TITLE
Enhancement: Do existence check for linked articles instead of downloads

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#222]
Consider adding "existence checks" as an option.

Rationale: Would gain speed and retain benefit of checking linked articles, but not checking the content of the linked article.

Method: 
This Gitea API returns a JSON structure that can be kept in memory to check if a TW article exists:

https://git.door43.org/api/v1/repos/unfoldingword/en_tw/git/trees/master?recursive=true&per_page=99999

**Comment by RobH123** [comment]
Ok, it seems that Gitea supplies a maximum of 12,000 entries at one time.

**Comment by mandolyte** [comment]
That max is configurable... what number would work so that pagination could
be avoided?

You can discuss with Rich


Cecil

**Comment by richmahn** [comment]
It is configurable, but for the whole API. It is usually best practice to avoid making the server serve everything but rather just keep querying and append results to an array until you get no results (or truncated is false, as mentioned above). It also tells you the total count when querying the first page, so you can also know when you have them all by that.

**Comment by richmahn** [comment]
Actually it looks like you will need to get to a page that does not return anything (i.e. `"tree": null`) to get `"truncated": false`. Not sure if that is common API procedure or not. I didn't write this.

![image](https://user-images.githubusercontent.com/2839925/145397282-159b9cdd-9d83-42ad-8818-9887a614ba7d.png)

**Comment by RobH123** [comment]
@richmahn cc @mandolyte Yes, I ended up writing an append loop and that wasn't hard once I realised that even the last page has _truncated_ set to false (as mentioned [above](https://github.com/unfoldingWord/uw-content-validation/issues/222#issuecomment-947370115)).
