### ISSUE TITLE
Make various columns narrower or wider

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/uw-content-validation#34]
Many columns in the results table are too wide.  Reduce the size of the following:
Resource
Priority
Chapter
Verse
Line
RowID
Character POS

Increase the width of:
Message

**Comment by RobH123** [comment]
@birchamp This repo is for the checks themselves. The only tables here are in the low-level demos.

I think you need to create the issue at https://github.com/unfoldingWord-box3/content-validation-app/issues.
