### ISSUE TITLE
checkTN_TSVDataRow() does not warn that occurrence notes does not match SupportReference

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/uw-content-validation#38]
This should generate warning:

`GEN\t1\t6\turb3\tfigs-imperative\t\t0\tLet there be an expanse…let it divide\tThese are commands. By commanding that the expanse should exist and that it divide the waters, God made it exist and divide the waters. (See: [[rc://en/ta/man/figs-parallelism]])`

**Comment by RobH123** [comment]
I need help on this one. See [this](https://unfoldingword.zulipchat.com/#narrow/stream/207529-wg-content/topic/TSV.20formats/near/191662142) and the convoluted thread following that. I would like to see the TN TSV spec clarified first.
