### ISSUE TITLE
Limit validation to checks for the selected books only

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/uw-content-validation#44]
TQs (and all other checks) should be limited to the current book(s) - not the entire resource

**Comment by PhotoNomad0** [comment]
@birchamp I think you mean to do tQ checking, but restrict to selected books only.

**Comment by RobH123** [comment]
I checked this @birchamp and this was always the case. Well, unless the code isn't/wasn't working as it should have been. But note that even one TQ book can be several hundreds of small files and JS file unzipping isn't the fastest in the world.

I would prefer that the calling app (which has a GUI) decides which repos (and which books in those repos) should be checked,.
