### ISSUE TITLE
Code directly fetches unconditionally original language files

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#51]
The snippet below is from `quote-check.js`. It unconditionally fetches a new copy of the original language text. 

If this were in tC Create, it would be fetching a new fresh copy for each row in a tN TSV (if I understand what it is doing correctly).

**Propose that this code be refactored to take originalUSFM as an input parameter.** Additionally, we should review any other cases where this module is fetching data. All data should be provided to it -- it should never fetch any on its own. Fetching must be left to the app using this code.

Is this agreeable?

```js
        let originalUSFM;
        // console.log(`Need to check against ${originalLanguageRepoCode}`);
        const getFile_ = (optionalCheckingOptions && optionalCheckingOptions.getFile) ? optionalCheckingOptions.getFile : getFileCached;
        if (originalLanguageRepoCode === 'UHB') {
            try {
                originalUSFM = await getFile_({ username, repository: originalLanguageRepoName, path: filename, branch });
                // console.log("Fetched file_content for", repoName, filename, typeof originalUSFM, originalUSFM.length);
            } catch (gcUHBerror) {
                console.log("ERROR: Failed to load", username, originalLanguageRepoCode, filename, branch, gcUHBerror.message);
                addNotice6({ priority: 601, message: "Failed to load", filename, location: `${ourLocation}: ${gcUHBerror}`, extra: originalLanguageRepoName });
            }
        } else if (originalLanguageRepoCode === 'UGNT') {
            try {
                originalUSFM = await getFile_({ username, repository: originalLanguageRepoName, path: filename, branch });
                // console.log("Fetched file_content for", repoName, filename, typeof originalUSFM, originalUSFM.length);
            } catch (gcUGNTerror) {
                console.log("ERROR: Failed to load", username, originalLanguageRepoCode, filename, branch, gcUGNTerror.message);
                addNotice6({ priority: 601, message: "Failed to load", filename, location: `${ourLocation}: ${gcUGNTerror}`, extra: originalLanguageRepoName });
            }
        }
```

**Comment by mandolyte** [comment]
I looked thru the code and did not find any other cases where this package was fetching files like this. So hopefully this is the only case.

**Comment by RobH123** [comment]
@mandolyte The code snippet you pasted is not quite fetching unconditionally. The third line pasted above allows for the calling package to pass through a getFile({username, repository, path, branch}) function in the `checkingOptions` (or similarly-named last) parameter of the checks that are called by the App. These options are already passed all the way down through all levels of the checks. Is that enough or do you need more? @PhotoNomad0 probably knows enough about both ends of things to help answer that question.

**Comment by mandolyte** [comment]
That may be OK then. But if the use case is to obtain the original language text and then loop thru it looking for a particular verse, then this could be very slow in tc-create. 

Assuming my concern is legit (and if not, just comment and close this issue), then consider divvying up the responsibilities between the CV pkg and the calling/using app so as to require the app to pass as a parameter the original language verse(s) for what is being validated.

Thanks!

**Comment by RobH123** [comment]
Ah, I understand better now @mandolyte. Yes, you can pass in `originalLanguageVerseText` in the [optionalCheckingOptions](https://github.com/unfoldingWord/uw-content-validation/blob/master/src/core/quote-check.js#L16) if you already have it (although this hasn't actually been tested yet).

**Comment by RobH123** [comment]
I documented the checkingOptions in the [ReadMe](https://unfoldingword.github.io/uw-content-validation/) (about half-way down). If you feel that does the job, feel free to close this issue @mandolyte.
