### ISSUE TITLE
Original Languages should not be validated

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#53]
In the general case, original languages (Greek and Hebrew) should not be validated, since a GL organization does not own them and are not responsible for maintaining them.

The only exception might be when the organization that owns the repos being validated is unfoldingWord, which actually *does* own them and is responsible.

**Comment by RobH123** [comment]
I think that's determined in the App now @mandolyte ?

**Comment by RobH123** [comment]
I'm not aware of any changes needed in the package. (If I'm wrong, just reopen the issue.)
