### ISSUE TITLE
Validation notices on empty support references

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#54]
From CV app, selecting Russian and Titus. The line in question has no support reference value.

![image](https://user-images.githubusercontent.com/1289437/94831995-61e43900-03db-11eb-8d7e-ea7a1ced66e9.png)

**Comment by RobH123** [comment]
I think it's because the SupportReference might be whitespace. Ah, line 77 contains a zero-width space only, and line 92 the same. Very hard for users to see or fix with existing tools. I think I've fixed it, but I don't have an easy way to setup an identical test.
