### ISSUE TITLE
Version 0.8.16: Ambiguous error message

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#61]
for BCS Hindi, the tQ repo exists (altho it uses an uppercase "Q"), but it has no manifest. And the "content" folder uses an uppercase "C", so things aren't in a standard location either. So at least two things wrong.

Here is the message as shown:
![image](https://user-images.githubusercontent.com/1289437/97574406-925ec900-19c1-11eb-9ee2-b4fd1ed4b54c.png)

**Comment by RobH123** [comment]
I think it's better to get them to rename the repo and the folder @mandolyte. If the CV package can't find the data, probably our other software won't be able to either.
