### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#63]
Just some notes and things that aren't that important...

- The GlBookPackageCheck demo: it would be nice to include the documented "wait" parameter in the code, but commented out (or set to 'N'; It wasn't immediately obvious what was being asked.
- The AllBookPackagesCheck demo  shows this react error:
```
Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
At another point, I thought I saw a different message about recursion being too deep (or to that effect)

**Comment by RobH123** [comment]
I think this issue is now obsolete.
