### ISSUE TITLE
Seeing messages with odd information

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#66]
Two things in particular:
1. This message appears to have JavaScript leftovers in it: `(not '57-TIT.usfm') [object Object]`
2. This message is claiming that an invalid book abbreviation: `Bad function call: should be given a valid book abbreviation`

Here is screenshot:

![image](https://user-images.githubusercontent.com/1289437/99963775-486ac800-2d60-11eb-8906-2524cb08ce44.png)

**Comment by RobH123** [comment]
This would have been the result of supplying too few parameters to the function.
