### ISSUE TITLE
Crash and lots of assertion errors - v0.9.1

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#67]
Given the number of these, perhaps the API has changed?

![image](https://user-images.githubusercontent.com/1289437/99964292-1148e680-2d61-11eb-9645-926fabb58108.png)

![image](https://user-images.githubusercontent.com/1289437/99964534-6be24280-2d61-11eb-9a84-850ef73974a4.png)

**Comment by RobH123** [comment]
@mandolyte Could it be this change: https://github.com/unfoldingWord/uw-content-validation/pull/64/files#diff-c92aca5d9a4825dc98c552ccdb9271e56d9ec52002744ee7178933d826576878R16

**Comment by RobH123** [comment]
Yes, this was a change in the API, sorry.
