### ISSUE TITLE
v0.9.2 fails to compile in tc-create-app

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#70]
It is missing material table:

![image](https://user-images.githubusercontent.com/1289437/101662363-6b130700-3a17-11eb-86f4-5a1420de9b5b.png)

Of course, should the demos folder even be in what is published to NPM?

**Comment by mandolyte** [comment]
v0.9.1 fails the same way.

but v0.8.16 is working. So I'll try to go with it for now.

**Comment by RobH123** [comment]
Fixed by https://github.com/unfoldingWord/uw-content-validation/pull/72
