### ISSUE TITLE
Update USFM Grammar package

### ISSUE THREAD

**Issue by RobH123** [unfoldingWord/uw-content-validation#83]
Discover why we get package errors

Check that USFM line numbers now account for blank lines. Could be that they're currently wrong???

**Comment by joelthe1** [comment]
Bumping this up: https://github.com/Bridgeconn/usfm-grammar/releases/tag/v2.0.0

**Comment by RobH123** [comment]
Yeah, sorry @joelthe1, I haven't been able to keep up with the last six months of changes. I'm upgrading it today -- seems there's some changes in how errors and warnings are passed back.

Also toJSON() seems to throw an exception on [this line in the UHB](https://git.door43.org/unfoldingWord/hbo_uhb/src/branch/master/15-EZR.usfm#L212) rather than returning a list of errors.

You can run [my current code](https://unfoldingword.github.io/uw-content-validation/#/Book%20Package%20Checker%20Demo?id=bookpackagecheck) from [here](https://unfoldingword.github.io/uw-content-validation/#/Book%20Package%20Checker%20Demo?id=bookpackagecheck) (with the default settings) and it has some extra logging still in it.

**Comment by joelthe1** [comment]
Yes @RobH123. We've made changes to `usfm-grammar` to throw an exception in case it encounters an error. These would have to be handled by your code appropriately. The warning would still be returned in the JSON.

**Comment by RobH123** [comment]
Ah, I guess that makes sense @joelthe1 because I'm using toJSON() as an unusual way to validate / find-errors-in the USFM. But I guess the disadvantage of an exception is that it only finds the first error in the USFM and then stops.

Is there any chance of updating your schema to handle the \w field inside a footnote mentioned above for the UHB?

**Comment by joelthe1** [comment]
Yes, @RobH123 that is a disadvantage of `usfm-grammar` but which is not unlike any other programming language grammar (e.g. `python`). I can tell you though that we are looking into more recent research in this space which might allow us to work around this problem in the future.

Also, for the `\w` Kavitha reminded me this: https://github.com/Bridgeconn/usfm-grammar/issues/86#issuecomment-718578839. Basically, the recommendation is to use `\+w` as per the USFM spec.
